// import bcrypt from "bcryptjs";
export const data = {
  quizquestions: [
    {
      question:
        "Q1: Which of the following is the correct syntax to print the message in C++ language?",
      option1: 'cout <<"Hello world!";',
      option2: " Cout << Hello world! ;",
      option3: "Out << Hello world!;",
      option4: " None of the above",
      answer: "option1",
      category: "clanguage",
    },
    {
      question: "Q2: Which of the following is the correct identifier?",
      option1: " $var_name",
      option2: " VAR_123",
      option3: " varname@",
      option4: " None of the above",
      answer: "option2",
      category: "clanguage",
    },
    {
      question: "Q3: Which of the following is the address operator?",
      option1: " @",
      option2: " #",
      option3: " &",
      option4: " %",
      answer: "option3",
      category: "clanguage",
    },
    {
      question:
        "Q4: Which of the following features must be supported by any programming language to become a pure object-oriented programming language?",
      option1: " Encapsulation",
      option2: " Inheritance",
      option3: " Polymorphism",
      option4: " All of the above",
      answer: "option4",
      category: "clanguage",
    },
    {
      question:
        "Q5: The programming language that has the ability to create new data types is called___.",
      option1: " Overloaded",
      option2: " Encapsulated",
      option3: " Reprehensible",
      option4: " Extensible",
      answer: "option4",
      category: "clanguage",
    },
    {
      question:
        "Q6:Which of the following is the original creator of the C++ language?",
      option1: " Dennis Ritchie",
      option2: " Ken Thompson",
      option3: " Bjarne Stroustrup",
      option4: " Brian Kernighan",
      answer: "option3",
      category: "clanguage",
    },
    {
      question:
        "Q7:Which of the following is the correct syntax to add the header file in the C++ program?",
      option1: " #include < userdefined>",
      option2: ' #include "userdefined.h" ',
      option3: ' < include > "userdefined.h " ',
      option4: " Both A and B",
      answer: "option4",
      category: "clanguage",
    },
    {
      question:
        "Q8:Which of the following is the correct syntax to read the single character to console in the C++ language?",
      option1: " Read ch()",
      option2: " Getline vh() ",
      option3: " get(ch) ",
      option4: " Scanf(ch)",
      answer: "option3",
      category: "clanguage",
    },
    {
      question:
        "Q9:Which of the following statements is correct about the formal parameters in C++?",
      option1: " Parameters with which functions are called",
      option2: " Parameters which are used in the definition of the function ",
      option3: " Variables other than passed parameters in a function ",
      option4: " Variables that are never used in the function",
      answer: "option1",
      category: "clanguage",
    },
    {
      question: "Q10:The C++ language is ______ object-oriented language.",
      option1: " Pure Object oriented",
      option2: " Not Object oriented",
      option3: " Semi Object-oriented or Partial Object-oriented ",
      option4: " None of the above",
      answer: "option3",
      category: "clanguage",
    },
    {
      question:
        "Q11:Which of the following comment syntax is correct to create a single-line comment in the C++ program?",
      option1: " //Comment",
      option2: " /Comment/",
      option3: " Comment// ",
      option4: " None of the above",
      answer: "option1",
      category: "clanguage",
    },
    {
      question: "Q12:C++ is a ___ type of language.",
      option1: " High-level language",
      option2: " Low-level language",
      option3: " Middle-level language ",
      option4: " None of the above",
      answer: "option3",
      category: "clanguage",
    },
    {
      question:
        "Q13:For inserting a new line in C++ program, which one of the following statements can be used?",
      option1: " \\n",
      option2: " \\r",
      option3: " \\a ",
      option4: " None of the above",
      answer: "option1",
      category: "clanguage",
    },
    {
      question: "Q14:Which one of the following represents the tab?",
      option1: " \\n",
      option2: " \\t",
      option3: " \\r",
      option4: " None of the above",
      answer: "option2",
      category: "clanguage",
    },
    {
      question:
        "Q15:Which of the following refers to characteristics of an array?",
      option1: " An array is a set of similar data items",
      option2: " An array is a set of distinct data items",
      option3: " An array can hold different types of datatypes ",
      option4: " None of the above",
      answer: "option1",
      category: "clanguage",
    },
  ],
};
